search='input[aria-label="Search"]'
size_btn='//*[@id="app"]//button[text()="32"]'
search_products='div[data-at="product-title"]'
pincode='input[aria-label="Enter Pincode"]'
apply_pincode_btn='//*[@id="app"]//button[text()="Apply"]'
add_to_bag_btn='button.addToBagButtonContainer'
view_bag_btn='button.addToBagButtonContainer'
proceed_to_buy_btn='button[data-at="continue-to-checkout"]'
proceed_to_pay_btn='//*[@id="app"]//div/button[text()="Proceed to Pay"]'
cart_iframe='iframe[title="Nykaa Fashion Cart"]'
item_heading='h1[data-at="product-name"] a'
move_to_wishlist_btn='button[data-at="move-to-wishlist"]'
back_btn_in_cart='//*[@id="app"]/header/a'
wishlist_btn='//*[@id="app"]//div[text()="Wishlist"]'
wishlist_item='div[data-at="product-title"]'